name: Type Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Run type check
        run: yarn tsc --noEmit
      - name: Test build
        run: yarn build 